
macintel_data = {
    "os_options": [
        {"platform": "MacIntel", "os_info": "Macintosh; Intel Mac OS X 14_7_4", "os_name": "macOS 14.7.4 Sonoma", "os_version": "14.7.4"},
        {"platform": "MacIntel", "os_info": "Macintosh; Intel Mac OS X 14_7_5", "os_name": "macOS 14.7.5 Sonoma", "os_version": "14.7.5"},
        {"platform": "MacIntel", "os_info": "Macintosh; Intel Mac OS X 15_3_1", "os_name": "macOS 15.3.1 Sequoia", "os_version": "15.3.1"},
        {"platform": "MacIntel", "os_info": "Macintosh; Intel Mac OS X 15_4_0", "os_name": "macOS 15.4.0 Sequoia", "os_version": "15.4.0"},
    ],

    "builtInAudioCard": [
        {"id": 1, "name": "Cirrus Logic CS4206", "platform": "MacIntel"},
        {"id": 2, "name": "Cirrus Logic CS4207", "platform": "MacIntel"},
        {"id": 3, "name": "Cirrus Logic CS4212", "platform": "MacIntel"},
        {"id": 4, "name": "Cirrus Logic CS4214", "platform": "MacIntel"},
        {"id": 5, "name": "Cirrus Logic CS4216", "platform": "MacIntel"},
        {"id": 6, "name": "Cirrus Logic CS4220", "platform": "MacIntel"},
        {"id": 7, "name": "Cirrus Logic CS4222", "platform": "MacIntel"},
        {"id": 8, "name": "Cirrus Logic CS4224", "platform": "MacIntel"},
        {"id": 9, "name": "Cirrus Logic CS4226", "platform": "MacIntel"},
        {"id": 10, "name": "Cirrus Logic CS4230", "platform": "MacIntel"},
        {"id": 11, "name": "Cirrus Logic CS4232", "platform": "MacIntel"},
        {"id": 12, "name": "Cirrus Logic CS4234", "platform": "MacIntel"},
        {"id": 13, "name": "Realtek ALC889", "platform": "MacIntel"},
        {"id": 14, "name": "Realtek ALC233", "platform": "MacIntel"},
        {"id": 15, "name": "Realtek ALC662", "platform": "MacIntel"},
        {"id": 16, "name": "Realtek ALC898", "platform": "MacIntel"},
        {"id": 17, "name": "Wolfson WM9712", "platform": "MacIntel"},
        {"id": 18, "name": "Wolfson WM8805", "platform": "MacIntel"},
        {"id": 19, "name": "Cirrus Logic CS4240", "platform": "MacIntel"},
        {"id": 20, "name": "Cirrus Logic CS4242", "platform": "MacIntel"},
        {"id": 21, "name": "Cirrus Logic CS4244", "platform": "MacIntel"},
        {"id": 22, "name": "Cirrus Logic CS4246", "platform": "MacIntel"},
        {"id": 23, "name": "Cirrus Logic CS4260", "platform": "MacIntel"},
        {"id": 24, "name": "Cirrus Logic CS4262", "platform": "MacIntel"},
        {"id": 25, "name": "Apple T2 Audio Controller", "platform": "MacIntel"}
    ],
    "microphone": [
        {"id": 1, "name": "Shure MV5 Digital Condenser Microphone", "platform": "MacIntel"},
        {"id": 2, "name": "Blue Yeti USB Microphone", "platform": "MacIntel"},
        {"id": 3, "name": "Audio-Technica AT2020USB+", "platform": "MacIntel"},
        {"id": 4, "name": "Rode NT-USB Mini", "platform": "MacIntel"},
        {"id": 5, "name": "Samson Meteor Mic", "platform": "MacIntel"},
        {"id": 6, "name": "Blue Snowball iCE", "platform": "MacIntel"},
        {"id": 7, "name": "Rode Podcaster", "platform": "MacIntel"},
        {"id": 8, "name": "Sennheiser MK 4 Digital", "platform": "MacIntel"},
        {"id": 9, "name": "AKG Lyra", "platform": "MacIntel"},
        {"id": 10, "name": "Elgato Wave:3", "platform": "MacIntel"},
        {"id": 11, "name": "Fifine K669B", "platform": "MacIntel"},
        {"id": 12, "name": "HyperX SoloCast", "platform": "MacIntel"},
        {"id": 13, "name": "JLab Talk Go", "platform": "MacIntel"},
        {"id": 14, "name": "Razer Seiren X", "platform": "MacIntel"},
        {"id": 15, "name": "MXL AC-404", "platform": "MacIntel"},
        {"id": 16, "name": "Movo UM700", "platform": "MacIntel"},
        {"id": 17, "name": "CAD U37", "platform": "MacIntel"},
        {"id": 18, "name": "Bluebird CM-100", "platform": "MacIntel"},
        {"id": 19, "name": "Boya BY-M1", "platform": "MacIntel"},
        {"id": 20, "name": "Sony ECM-B1M", "platform": "MacIntel"},
        {"id": 21, "name": "Sennheiser e835", "platform": "MacIntel"},
        {"id": 22, "name": "Audio-Technica ATR2100x-USB", "platform": "MacIntel"},
        {"id": 23, "name": "Rode Procaster", "platform": "MacIntel"},
        {"id": 24, "name": "Audio-Technica AT2035", "platform": "MacIntel"},
        {"id": 25, "name": "Neumann TLM 102", "platform": "MacIntel"}
    ],
    "headphone": [
        {"id": 1, "name": "Apple AirPods Pro", "platform": "MacIntel"},
        {"id": 2, "name": "Bose QuietComfort 35 II", "platform": "MacIntel"},
        {"id": 3, "name": "Sony WH-1000XM4", "platform": "MacIntel"},
        {"id": 4, "name": "Sennheiser Momentum 3 Wireless", "platform": "MacIntel"},
        {"id": 5, "name": "Bowers & Wilkins PX7", "platform": "MacIntel"},
        {"id": 6, "name": "Beats Studio3 Wireless", "platform": "MacIntel"},
        {"id": 7, "name": "AKG N700NC M2", "platform": "MacIntel"},
        {"id": 8, "name": "Audio-Technica ATH-M50x", "platform": "MacIntel"},
        {"id": 9, "name": "Bose SoundLink Around-Ear", "platform": "MacIntel"},
        {"id": 10, "name": "Jabra Elite 85h", "platform": "MacIntel"},
        {"id": 11, "name": "Plantronics BackBeat Pro 2", "platform": "MacIntel"},
        {"id": 12, "name": "Marshall Monitor II A.N.C.", "platform": "MacIntel"},
        {"id": 13, "name": "Grado SR80x", "platform": "MacIntel"},
        {"id": 14, "name": "Shure AONIC 50", "platform": "MacIntel"},
        {"id": 15, "name": "Skullcandy Crusher ANC", "platform": "MacIntel"},
        {"id": 16, "name": "Philips SHP9500", "platform": "MacIntel"},
        {"id": 17, "name": "Sennheiser HD 560S", "platform": "MacIntel"},
        {"id": 18, "name": "Beyerdynamic DT 990 Pro", "platform": "MacIntel"},
        {"id": 19, "name": "AKG K702", "platform": "MacIntel"},
        {"id": 20, "name": "Sony MDR-7506", "platform": "MacIntel"},
        {"id": 21, "name": "Audio-Technica ATH-AD700X", "platform": "MacIntel"},
        {"id": 22, "name": "Sennheiser HD 660 S", "platform": "MacIntel"},
        {"id": 23, "name": "Bowers & Wilkins P7 Wireless", "platform": "MacIntel"},
        {"id": 24, "name": "Grado SR225e", "platform": "MacIntel"},
        {"id": 25, "name": "Apple AirPods Max", "platform": "MacIntel"}
    ],
    "videoinput": [
        {"id": 1, "name": "Built-in FaceTime HD Camera", "platform": "MacIntel"},
        {"id": 2, "name": "Apple FaceTime Camera", "platform": "MacIntel"},
        {"id": 3, "name": "Integrated Mac Webcam", "platform": "MacIntel"},
        {"id": 4, "name": "MacBook Pro FaceTime HD Camera", "platform": "MacIntel"},
        {"id": 5, "name": "MacBook Air FaceTime Camera", "platform": "MacIntel"},
        {"id": 6, "name": "Apple iSight Camera", "platform": "MacIntel"},
        {"id": 7, "name": "Retina FaceTime HD Camera", "platform": "MacIntel"},
        {"id": 8, "name": "iMac Integrated Camera", "platform": "MacIntel"},
        {"id": 9, "name": "Mac Studio Integrated Camera", "platform": "MacIntel"},
        {"id": 10, "name": "Mac Mini FaceTime Camera", "platform": "MacIntel"},
        {"id": 11, "name": "Logitech BRIO Ultra HD Pro", "platform": "MacIntel"},
        {"id": 12, "name": "Logitech C920S HD Pro", "platform": "MacIntel"},
        {"id": 13, "name": "Razer Kiyo Pro", "platform": "MacIntel"},
        {"id": 14, "name": "Aukey PC-LM1E", "platform": "MacIntel"},
        {"id": 15, "name": "Anker PowerConf C300", "platform": "MacIntel"}
    ],
    "GPU": [
    {"id": 1,  "name": "AMD Radeon(TM) RX 6600",     "architecture": "rdna2",   "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440","3840x2160"],             "prod_code": "0x73FF"},
    {"id": 2,  "name": "AMD Radeon(TM) RX 6600 XT",  "architecture": "rdna2",   "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440","3840x2160"],             "prod_code": "0x73FF"},
    {"id": 3,  "name": "AMD Radeon(TM) RX 570",      "architecture": "polaris", "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440"],                         "prod_code": "0x67DF"},
    {"id": 4,  "name": "AMD Radeon(TM) RX 580",      "architecture": "polaris", "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440"],                         "prod_code": "0x67DF"},
    {"id": 5,  "name": "AMD Radeon(TM) Pro WX 7100", "architecture": "polaris", "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440"],                         "prod_code": "0x67C4"},
    {"id": 6,  "name": "AMD Radeon(TM) RX 6700 XT",  "architecture": "rdna2",   "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440","3840x2160","7680x4320"], "prod_code": "0x73DF"},
    {"id": 7,  "name": "AMD Radeon(TM) RX 6750 XT",  "architecture": "rdna2",   "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440","3840x2160","7680x4320"], "prod_code": "0x73DF"},
    {"id": 8,  "name": "AMD Radeon(TM) RX 5700",     "architecture": "navi",    "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440","3840x2160"],             "prod_code": "0x731F"},
    {"id": 9,  "name": "AMD Radeon(TM) RX 5700 XT",  "architecture": "navi",    "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440","3840x2160"],             "prod_code": "0x731F"},
    {"id": 10, "name": "AMD Radeon(TM) RX 6800",     "architecture": "rdna2",   "type": "discrete", "platform": "MacIntel", "resolution": ["1920x1080","2560x1440","3840x2160","7680x4320"], "prod_code": "0x73BF"}
    ]

}